# https://github.com/gesiscss/jhub_shibboleth_auth/tree/78fbca3a5319faf5e8c1787794117dd30e3bf1c8/docker/k8s_hub
FROM gesiscss/k8s-hub:cc865bd-v1.4.0

USER root
COPY templates /srv/jhub_custom_templates
USER ${NB_USER}
