# https://github.com/gesiscss/jhub_shibboleth_auth/tree/f1ce8692bdea0c02c1f4cdac643101323bf45ba7/docker/k8s_hub
FROM gesiscss/k8s-hub:0e1225e-e0c6f7f9

USER root
COPY templates /srv/jhub_custom_templates
USER ${NB_USER}
