# chart version version 12.0.2
# WARNING: the above chart version is read by fabfile.py, so upgrade chart version above whenever you upgrade the prometheus helm chart
# https://github.com/prometheus-community/helm-charts/tree/prometheus-12.0.2

alertmanager:
  # TODO
  enabled: false
pushgateway:
  enabled: false

server:
 nodeSelector:
   base: worker
  service:
    type: NodePort
    nodePort: 30073
    # used in grafana_config.yaml: datasources.datasources.yaml.datasources.url
    servicePort: 80  # default
  resources:
    requests:
      cpu: "1"
      memory: 8Gi
    limits:
      cpu: "4"
      memory: 32Gi
  persistentVolume:
    # has no effect when using nfs: this is a min limit not a max
    size: 96Gi
#    existingClaim:
  retention: 60d

#kubeStateMetrics:
#  nodeSelector:
#    base: worker
#  resources:
