#!/bin/bash
set -euo pipefail
set -x
appendix_dir="$(dirname "$0")"
mkdir -p /etc/jupyter
# add custom js
sed -i 's|{binder_url}|'"$BINDER_URL"'|g' "${appendix_dir}/static/custom.js"
sed -i 's|{repo_url}|'"$REPO_URL"'|g' "${appendix_dir}/static/custom.js"
if [ ! -d ~/.jupyter/custom ]
then
    mkdir -p ~/.jupyter/custom
fi
cat "${appendix_dir}/static/custom.js" >> ~/.jupyter/custom/custom.js
# add and register custom templates and config
cp -r "${appendix_dir}/templates" /etc/jupyter/binder_templates
cat "${appendix_dir}/extra_notebook_config.py" >> /etc/jupyter/jupyter_notebook_config.py
# ensure /etc/jupyter has read+listdir permissions for all
chmod -R a+rX /etc/jupyter
