apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-gesisbinder
spec:
  schedule: "*/30 * * * *"
  # Setting a limit to 0 corresponds to keeping none of the corresponding kind of jobs after they finish.
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        metadata:
          name: update-gesisbinder
        spec:
          restartPolicy: Never
          containers:
          - name: update-gesisbinder
            image: python:3.7.4-stretch
            command: ["/bin/sh"]
            args: ["-c", "cd ~ && git config --global http.sslVerify false && git clone https://github.com/gesiscss/orc.git orc_repo && pip install -r orc_repo/gesisbinder/bot/requirements.txt --quiet && python orc_repo/gesisbinder/bot/bot.py"]
            env:
              - name: GL_BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: bot-data
                    key: token
              - name: GL_BOT_NAME
                valueFrom:
                  secretKeyRef:
                    name: bot-data
                    key: name
              - name: GL_BOT_EMAIL
                valueFrom:
                  secretKeyRef:
                    name: bot-data
                    key: email
